name: Publish into S3
on:
  push:
    branches:
      - '*'
      - '**'
      - '!releases/*'
      - '!releases/*/*'
      - '!releases/**'
jobs:
  build:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5' # The Go version to download (if necessary) and use.
      - run: go mod tidy
        name: download dependencies
      - run: go build
        name: build binary
      - run: mv cli linux
        name: rename binary
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload to S3
        run: aws s3 cp linux s3://${{ secrets.AWS_BUCKET }}/repositories/binaries/cli/snapshots/1.0.0.${{ github.run_id }}.${{ github.run_number }}/linux

  macOS:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5' # The Go version to download (if necessary) and use.
      - run: go mod tidy
        name: download dependencies
      - run: go build
        name: build binary
      - run: mv cli macos
        name: rename binary
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload to S3
        run: aws s3 cp macos s3://${{ secrets.AWS_BUCKET }}/repositories/binaries/cli/snapshots/1.0.0.${{ github.run_id }}.${{ github.run_number }}/macos