name: Deploy
on:
  push:
    branches:
      - '*'
      - '**'
      - '!releases/*'
      - '!releases/*/*'
      - '!releases/**'
jobs:
  build:
    name: linux
    runs-on: ubuntu-latest
    env:
      GITHUB_LABEL: SNAPSHOT
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5' # The Go version to download (if necessary) and use.
      - run: go mod tidy
        name: download dependencies
      - run: ./build/build.sh
        name: build binary
      - name: Read Version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload to S3
        run: |
          VERSION=$(cat "docs/version")
          aws s3 cp ant s3://${{ secrets.AWS_BUCKET }}/repositories/binaries/ant/snapshots/$VERSION-$GITHUB_LABEL.$GITHUB_RUN_ID.$GITHUB_RUN_NUMBER/linux/application
          aws s3 cp internal/commands/lint/schema.json s3://${{ secrets.AWS_BUCKET }}/repositories/binaries/ant/snapshots/1.0.0.${{ github.run_id }}.${{ github.run_number }}/linux/schema.json

  macOS:
    name: macos
    runs-on: macos-latest
    env:
      GITHUB_LABEL: snapshot
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5' # The Go version to download (if necessary) and use.
      - run: go mod tidy
        name: download dependencies
      - run: ./build/build.sh
        name: build binary
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload to S3
        run: aws s3 cp ant s3://${{ secrets.AWS_BUCKET }}/repositories/binaries/ant/snapshots/1.0.0.${{ github.run_id }}.${{ github.run_number }}/macos/application
      - name: upload to schema
        run: aws s3 cp internal/commands/lint/schema.json s3://${{ secrets.AWS_BUCKET }}/repositories/binaries/ant/snapshots/1.0.0.${{ github.run_id }}.${{ github.run_number }}/macos/schema.json

  windows:
    name: windows
    runs-on: windows-latest
    env:
      GITHUB_LABEL: snapshot
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5' # The Go version to download (if necessary) and use.
      - run: go mod tidy
        name: download dependencies
      - run: ./build/build.sh
        name: build binary
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload to S3
        run: aws s3 cp ant.exe s3://${{ secrets.AWS_BUCKET }}/repositories/binaries/ant/snapshots/1.0.0.${{ github.run_id }}.${{ github.run_number }}/windows/application.exe
      - name: upload to schema
        run: aws s3 cp internal/commands/lint/schema.json s3://${{ secrets.AWS_BUCKET }}/repositories/binaries/ant/snapshots/1.0.0.${{ github.run_id }}.${{ github.run_number }}/windows/schema.json