name: Deploy
on:
  push:
    branches:
      - '*'
      - '**'
      - '!releases/*'
      - '!releases/*/*'
      - '!releases/**'
jobs:
  build:
    name: linux
    runs-on: ubuntu-latest
    env:
      GITHUB_LABEL: SNAPSHOT
      S3_DIRECTORY: linux
      SECRET_AWS_BUCKET: ${{ secrets.AWS_BUCKET  }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5' # The Go version to download (if necessary) and use.
      - run: go mod tidy
        name: download dependencies
      - run: ./build/build.sh
        name: build binary
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload to S3
        run: ./build/publish.sh

  macOS:
    name: macos
    runs-on: macos-latest
    env:
      GITHUB_LABEL: SNAPSHOT
      S3_DIRECTORY: macos
      SECRET_AWS_BUCKET: ${{ secrets.AWS_BUCKET  }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5' # The Go version to download (if necessary) and use.
      - run: go mod tidy
        name: download dependencies
      - run: ./build/build.sh
        name: build binary
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload to S3
        run: ./build/publish.sh

  windows:
    name: windows
    runs-on: windows-latest
    env:
      GITHUB_LABEL: SNAPSHOT
      S3_FILE: ant.exe
      S3_DIRECTORY: windows
      SECRET_AWS_BUCKET: ${{ secrets.AWS_BUCKET  }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5' # The Go version to download (if necessary) and use.
      - run: go mod tidy
        name: download dependencies
      - run: ./build/build.sh
        name: build binary
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload to S3
        run: ./build/publish.sh
        